# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Action(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, put_siren: bool=None, showme_later: bool=None, other_actions: List[str]=None):  # noqa: E501
        """Action - a model defined in Swagger

        :param put_siren: The put_siren of this Action.  # noqa: E501
        :type put_siren: bool
        :param showme_later: The showme_later of this Action.  # noqa: E501
        :type showme_later: bool
        :param other_actions: The other_actions of this Action.  # noqa: E501
        :type other_actions: List[str]
        """
        self.swagger_types = {
            'put_siren': bool,
            'showme_later': bool,
            'other_actions': List[str]
        }

        self.attribute_map = {
            'put_siren': 'putSiren',
            'showme_later': 'showmeLater',
            'other_actions': 'otherActions'
        }
        self._put_siren = put_siren
        self._showme_later = showme_later
        self._other_actions = other_actions

    @classmethod
    def from_dict(cls, dikt) -> 'Action':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The action of this Action.  # noqa: E501
        :rtype: Action
        """
        return util.deserialize_model(dikt, cls)

    @property
    def put_siren(self) -> bool:
        """Gets the put_siren of this Action.

        important alerts  # noqa: E501

        :return: The put_siren of this Action.
        :rtype: bool
        """
        return self._put_siren

    @put_siren.setter
    def put_siren(self, put_siren: bool):
        """Sets the put_siren of this Action.

        important alerts  # noqa: E501

        :param put_siren: The put_siren of this Action.
        :type put_siren: bool
        """
        if put_siren is None:
            raise ValueError("Invalid value for `put_siren`, must not be `None`")  # noqa: E501

        self._put_siren = put_siren

    @property
    def showme_later(self) -> bool:
        """Gets the showme_later of this Action.

        intented to show the alerts later  # noqa: E501

        :return: The showme_later of this Action.
        :rtype: bool
        """
        return self._showme_later

    @showme_later.setter
    def showme_later(self, showme_later: bool):
        """Sets the showme_later of this Action.

        intented to show the alerts later  # noqa: E501

        :param showme_later: The showme_later of this Action.
        :type showme_later: bool
        """
        if showme_later is None:
            raise ValueError("Invalid value for `showme_later`, must not be `None`")  # noqa: E501

        self._showme_later = showme_later

    @property
    def other_actions(self) -> List[str]:
        """Gets the other_actions of this Action.

        any other events  # noqa: E501

        :return: The other_actions of this Action.
        :rtype: List[str]
        """
        return self._other_actions

    @other_actions.setter
    def other_actions(self, other_actions: List[str]):
        """Sets the other_actions of this Action.

        any other events  # noqa: E501

        :param other_actions: The other_actions of this Action.
        :type other_actions: List[str]
        """
        if other_actions is None:
            raise ValueError("Invalid value for `other_actions`, must not be `None`")  # noqa: E501

        self._other_actions = other_actions
