# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlertID(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alert_id: str=None):  # noqa: E501
        """AlertID - a model defined in Swagger

        :param alert_id: The alert_id of this AlertID.  # noqa: E501
        :type alert_id: str
        """
        self.swagger_types = {
            'alert_id': str
        }

        self.attribute_map = {
            'alert_id': 'alertId'
        }
        self._alert_id = alert_id

    @classmethod
    def from_dict(cls, dikt) -> 'AlertID':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The alertID of this AlertID.  # noqa: E501
        :rtype: AlertID
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alert_id(self) -> str:
        """Gets the alert_id of this AlertID.


        :return: The alert_id of this AlertID.
        :rtype: str
        """
        return self._alert_id

    @alert_id.setter
    def alert_id(self, alert_id: str):
        """Sets the alert_id of this AlertID.


        :param alert_id: The alert_id of this AlertID.
        :type alert_id: str
        """
        if alert_id is None:
            raise ValueError("Invalid value for `alert_id`, must not be `None`")  # noqa: E501

        self._alert_id = alert_id
