# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.alert import Alert  # noqa: F401,E501
from swagger_server import util


class AlertArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alerts: List[Alert]=None):  # noqa: E501
        """AlertArray - a model defined in Swagger

        :param alerts: The alerts of this AlertArray.  # noqa: E501
        :type alerts: List[Alert]
        """
        self.swagger_types = {
            'alerts': List[Alert]
        }

        self.attribute_map = {
            'alerts': 'alerts'
        }
        self._alerts = alerts

    @classmethod
    def from_dict(cls, dikt) -> 'AlertArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The alertArray of this AlertArray.  # noqa: E501
        :rtype: AlertArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alerts(self) -> List[Alert]:
        """Gets the alerts of this AlertArray.

        contains all the array  # noqa: E501

        :return: The alerts of this AlertArray.
        :rtype: List[Alert]
        """
        return self._alerts

    @alerts.setter
    def alerts(self, alerts: List[Alert]):
        """Sets the alerts of this AlertArray.

        contains all the array  # noqa: E501

        :param alerts: The alerts of this AlertArray.
        :type alerts: List[Alert]
        """
        if alerts is None:
            raise ValueError("Invalid value for `alerts`, must not be `None`")  # noqa: E501

        self._alerts = alerts
